version: '2'
services:
    zookeeper:
        image: zookeeper:3.4
        #container_name: zookeeper
        restart: always

    nimbus:
        build: storm
        #container_name: nimbus
        command: storm nimbus
        depends_on:
            - zookeeper
        links:
            - zookeeper
        restart: always
        ports:
            - 6627:6627
        volumes:
            - ./storm/conf:/conf

    supervisor:
        build: storm
        #container_name: supervisor
        command: storm supervisor
        depends_on:
            - nimbus
            - zookeeper
        links:
            - nimbus
            - zookeeper
        restart: always
        volumes:
            - ./storm/conf:/conf


    sui:
        build: storm
        command: storm ui 
        depends_on:
            - nimbus
            - zookeeper
        links:
            - nimbus
            - zookeeper
        restart: always
        ports:
            - "49080:8080" 
        volumes:
            - ./storm/conf:/conf


    streamparse:
        build: streamparse
        command: /entrypoint.sh 
        depends_on:
            - nimbus
        links:
            - nimbus
        restart: always
        volumes:
            - ./streamparse/tasks:/tasks
